.PHONY: clean All

All:
	@echo "----------Building project:[ laba1_chast1 - Debug ]----------"
	@"$(MAKE)" -f  "laba1_chast1.mk"
clean:
	@echo "----------Cleaning project:[ laba1_chast1 - Debug ]----------"
	@"$(MAKE)" -f  "laba1_chast1.mk" clean
